In [1]:
import numpy as np
import matplotlib.pyplot as plt
import gym
import pygame
import requests
import json
import numpy as np
from pattern import Pattern
from game import Game

pygame 2.5.2 (SDL 2.28.3, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html


### If not having question file or new question required, run this cell

In [17]:
url = "https://proconvn.duckdns.org"
headers = {"Authorization": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIsIm5hbWUiOiJQVElUIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE3MjgwMzc3MzgsImV4cCI6MTcyODIxMDUzOH0.RTXssYMXXHnlJIXHx-mIrirH5dFF-HjsWcESnbc46EA"}
question_id = 72
# question = requests.get(f"{url}/question/{question_id}", headers=headers).json()

# with open('question.json', 'w') as f:
#     json.dump(question, f, indent=4)

In [3]:
f = open('question.json', 'r')
question = json.load(f)

In [4]:
def get_info(question) :
    question_data = json.loads(question['question_data'])
    board = question_data['board']
    general = question_data['general']

    #preprocess board
    height = board['height']
    width = board['width']
    start_board = board['start']
    end_board = board['goal']
    start_board = np.array(start_board)
    end_board = np.array(end_board)

    #preprocess general
    n = general['n']

    general_patterns = []
    for i in general["patterns"]:
        p = i["p"]
        width = i["width"]
        height = i["height"]
        cells = i["cells"]
        cells = np.array(cells)
        general_patterns.append(Pattern(width, height, board = cells))
    return start_board, end_board, general_patterns

In [5]:
start_board, end_board, general_patterns = get_info(question)
print(start_board.shape)
print(end_board.shape)

(128, 64)
(128, 64)


In [27]:
m = start_board.shape[0]
n = start_board.shape[1]
print(m,n)

game = Game(m, n, 20, start_board, end_board, general_patterns)

128 64
3503240


In [7]:
def check(board, final_board, x,y,p,q):
    while x < 0: x+=1
    while y < 0: y+=1
    if board[x][y] == final_board[x][y]:
        return False
    return True

In [8]:
print(game.grid.board)

[[3 2 1 ... 2 0 2]
 [0 1 3 ... 3 3 1]
 [0 3 2 ... 3 3 2]
 ...
 [1 2 3 ... 1 2 0]
 [3 2 3 ... 2 0 1]
 [0 1 1 ... 1 0 3]]


In [9]:
cur_board = game.grid.board.copy()
final_board = game.final_grid.board.copy()

In [10]:
def cntDiff(m, n, cur_board, final_board):
    cnt=0
    for i in range(m):
        for j in range(n):
            if(cur_board[i][j] != final_board[i][j]): cnt+=1
    print(cnt)
    return cnt

#### Count the number of valid move

In [11]:
# cnt = 0
# for i in range(0, len(game.dict)):
#     # if i % 500 == 0: 
#     x,y, direction, id = game.dict[i]
#     p,q,type = game.grid.patterns[id].p, game.grid.patterns[id].q, game.grid.patterns[id].id
#     if(not check(cur_board, final_board, x,y,p,q)): continue
#     cnt += 1
# print("Numbebr of valid moves: ", cnt)

In [11]:
best_reward = 9999999

In [13]:
for i in range(0, len(game.dict)):
    # if i % 500 == 0: 
    x,y, direction, id = game.dict[i]
    p,q,type = game.grid.patterns[id].p, game.grid.patterns[id].q, game.grid.patterns[id].id
    # if(not check(cur_board, final_board, x,y,p,q)): continue
    board, reward, done, _, _= game.fake_step(i)
    if reward < best_reward:
    # if True:
        print(f"step {i}: x = {x}, y = {y}, direction = {direction}, p = {p}, q = {q}, type = {type} with reward = {reward}")
        print(cntDiff(m, n, board, final_board))
        best_reward = reward
    if done:
        print("found")
        #save this pattern to file
        x,y, direction, p = game.dict[i]
        #example: {"n": 1, "ops": [{"x": 1, "y": 1, "s": 1, "p": 1}]}
        with open('answer.json', 'w') as f:
            json.dump({"n": 1, "ops": [{"x": x, "y": y, "s": direction, "p": p}]}, f, indent=4)
        break
    if i % 10000 == 0: print(board)
else: print('not found')

step 0: x = 0, y = 0, direction = 0, p = 1, q = 1, type = 1 with reward = 1575
[[2 1 3 ... 0 2 3]
 [0 1 3 ... 3 3 1]
 [0 3 2 ... 3 3 2]
 ...
 [1 2 3 ... 1 2 0]
 [3 2 3 ... 2 0 1]
 [0 1 1 ... 1 0 3]]
step 2: x = 0, y = 2, direction = 0, p = 1, q = 1, type = 1 with reward = 1574
step 3: x = 0, y = 3, direction = 0, p = 1, q = 1, type = 1 with reward = 1569
step 8: x = 0, y = 8, direction = 0, p = 1, q = 1, type = 1 with reward = 1567
step 15: x = 0, y = 15, direction = 0, p = 1, q = 1, type = 1 with reward = 1565
step 150: x = 2, y = 22, direction = 0, p = 1, q = 1, type = 1 with reward = 1564
step 308: x = 4, y = 52, direction = 0, p = 1, q = 1, type = 1 with reward = 1563
step 342: x = 5, y = 22, direction = 0, p = 1, q = 1, type = 1 with reward = 1562
step 436: x = 6, y = 52, direction = 0, p = 1, q = 1, type = 1 with reward = 1561
step 592: x = 9, y = 16, direction = 0, p = 1, q = 1, type = 1 with reward = 1559
step 743: x = 11, y = 39, direction = 0, p = 1, q = 1, type = 1 with rewa

KeyboardInterrupt: 

In [38]:
'''s: hướng di chuyển trong phép biến đổi. Trong đó: top = 0, bottom = 1, left = 2,right = 3.'''
_,reward,_,_,_ = game.fake_step(game.convert(0,7,2,10))
print(reward)
print(m*n-reward)

2268
5924


In [31]:
#take one step


6137


In [24]:
def solve(question):
    return {"n": 1, "ops": [{"x": 0, "y": 7, "s": 2, "p": 10}]}

In [25]:
steps = solve(question)

# send your answer to server
try:
    payload = {"question_id": question_id, "answer_data": steps}
    res = requests.post(f"{url}/answer", json=payload, headers=headers).json()

except requests.exceptions.RequestException as e:
    print(f"Error: {e}")
#  get your answer id
answer_id = res["id"]

# get your answer and score from server


In [15]:
print(res)

{'message': 'Unauthorized'}


In [26]:
answer = requests.get(f"{url}/answer/{answer_id}", headers=headers).json()
score_data = json.loads(answer["score_data"])
print('match count: ', score_data["match_count"])
print("final score:", score_data["final_score"])

match count:  5917
final score: 5914.7


In [14]:
start_board = np.load('board.npy')
print(start_board)

[[2 2 1 ... 0 0 0]
 [2 3 1 ... 1 3 0]
 [1 2 2 ... 0 3 2]
 ...
 [3 2 0 ... 1 2 1]
 [1 3 3 ... 1 1 3]
 [0 2 3 ... 1 0 3]]


In [12]:
game2 = Game(16,16,20)

1254784


In [13]:
cur_board = game2.grid.board.copy()
print(cur_board)

[[1 0 3 1 2 1 2 2 0 2 0 3 0 0 3 2]
 [2 0 0 1 0 2 2 2 1 2 0 2 0 2 2 2]
 [3 1 0 1 0 2 2 3 0 2 1 1 3 0 3 2]
 [1 2 0 2 1 2 1 0 2 2 3 3 3 2 3 3]
 [3 2 0 2 0 3 3 2 1 3 1 2 0 3 2 1]
 [2 2 2 3 1 2 0 1 0 3 3 2 0 1 2 1]
 [3 2 1 1 3 3 2 1 0 1 0 3 3 2 0 3]
 [2 2 2 0 1 1 1 2 3 3 2 0 3 0 1 3]
 [1 0 2 0 1 3 3 0 3 2 1 3 2 0 3 2]
 [2 1 1 0 3 0 0 3 1 0 2 2 2 2 2 1]
 [1 0 2 2 0 3 3 3 0 0 0 1 1 0 3 3]
 [3 1 0 2 3 2 0 2 2 1 0 3 0 1 2 0]
 [0 3 1 1 3 2 1 1 0 2 2 2 1 1 0 0]
 [0 1 2 2 2 1 2 1 0 2 2 0 3 1 0 1]
 [1 2 1 1 3 1 0 3 0 1 1 2 0 0 3 2]
 [1 0 0 1 3 2 0 3 0 0 3 3 3 3 3 2]]


In [26]:
board, reward, done, _, _= game2.fake_step(game2.convert(0,0,0,0))

1566