In [1]:
import numpy as np
import matplotlib.pyplot as plt
import gym
import pygame
import requests
import json
import numpy as np
from pattern import Pattern
from game import Game

pygame 2.5.2 (SDL 2.28.3, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html


### IF not having question file or new question required, run this cell

In [2]:
url = "https://proconvn.duckdns.org"
headers = {"Authorization": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIsIm5hbWUiOiJQVElUIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE3MjcwODE4NzAsImV4cCI6MTcyNzI1NDY3MH0.q_v10XqiMVC4q44Tcw3xewdjDPzKIct7eeAFP_0Tvtg"}
question_id = 72
# question = requests.get(f"{url}/question/{question_id}", headers=headers).json()

# with open('question.json', 'w') as f:
#     json.dump(question, f, indent=4)

In [3]:
def get_info(question) :
    question_data = json.loads(question['question_data'])
    board = question_data['board']
    general = question_data['general']

    #preprocess board
    height = board['height']
    width = board['width']
    start_board = board['start']
    end_board = board['goal']
    start_board = np.array(start_board)
    end_board = np.array(end_board)

    #preprocess general
    n = general['n']

    general_patterns = []
    for i in general["patterns"]:
        p = i["p"]
        width = i["width"]
        height = i["height"]
        cells = i["cells"]
        cells = np.array(cells)
        general_patterns.append(Pattern(width, height, board = cells))
    return start_board, end_board, general_patterns

In [ ]:
start_board, end_board, general_patterns = get_info(question)
print(start_board.shape)
print(end_board.shape)

In [ ]:
game = Game(32, 32, 20, start_board, end_board, general_patterns)

In [4]:
print(game.grid.board)

[[1 0 2 ... 1 1 1]
 [1 2 0 ... 1 3 3]
 [3 2 3 ... 3 0 2]
 ...
 [3 0 0 ... 3 1 0]
 [3 2 3 ... 3 1 1]
 [1 0 1 ... 3 3 2]]


In [5]:
action = game.convert_back(255, 255, 3, 24)
print(action)

26112099


In [6]:

state, reward, done, _ = game.step(action)
print(game.grid.board)

255 255 3 24
[[2 2 1 ... 3 0 2]
 [0 2 2 ... 1 2 0]
 [0 1 3 ... 0 1 3]
 ...
 [2 0 0 ... 3 1 2]
 [3 2 2 ... 3 0 2]
 [0 3 2 ... 0 2 3]]


In [7]:
print(reward)

0.0013123359580052493


1
2
2
2
4
4
4
8
8
8
16
16
16
32
32
32
64
64
64
128
128
128
256
256
256
10674304


In [11]:
N_DISCRETE_ACTIONS = 10674304
print(dict[N_DISCRETE_ACTIONS-1])

[255, 255, 3, 24]
