In [1]:
import numpy as np
import matplotlib.pyplot as plt
import gym
import pygame


In [2]:
from game import Game

In [3]:
n = 32
m = 32
cell_size = 20
game = Game(m , n ,cell_size)


In [4]:
print(game.grid.board)

[[1 0 2 ... 1 1 1]
 [1 2 0 ... 1 3 3]
 [3 2 3 ... 3 0 2]
 ...
 [3 0 0 ... 3 1 0]
 [3 2 3 ... 3 1 1]
 [1 0 1 ... 3 3 2]]


In [5]:
action = game.convert_back(255, 255, 3, 24)
print(action)

26112099


In [6]:

state, reward, done, _ = game.step(action)
print(game.grid.board)

255 255 3 24
[[2 2 1 ... 3 0 2]
 [0 2 2 ... 1 2 0]
 [0 1 3 ... 0 1 3]
 ...
 [2 0 0 ... 3 1 2]
 [3 2 2 ... 3 0 2]
 [0 3 2 ... 0 2 3]]


In [7]:
print(reward)

0.0013123359580052493


In [5]:
dict = []
for b in range(25):
    sz = int((b-1)/3+1)
    sz = 2 ** (sz)
    print(sz)
    for a in range(3):  
        for x in range(-sz + 1,256):
            for y in range(-sz + 1,256):
                        dict.append([x, y, a, b])
print(len(dict))
                

2016285


In [7]:
print(dict[2016284])

[255, 255, 2, 7]
