In [9]:
import numpy as np
import matplotlib.pyplot as plt
import gym
import pygame
import requests
import json
import numpy as np
import sys
import os

sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '../..')))

from pattern import Pattern
from game import Game

### If not having question file or new question required, run this cell

In [10]:
question_id = 70

In [18]:
url = "https://proconvn.duckdns.org"
headers = {"Authorization": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIsIm5hbWUiOiJQVElUIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE3MjgyMTE5MzYsImV4cCI6MTcyODM4NDczNn0.fPkOgq9m6Z3_vbRFaL0EUTmK2wioCbuCqnpxKrmTkLA"}

question = requests.get(f"{url}/question/{question_id}", headers=headers).json()

with open('question.json', 'w') as f:
    json.dump(question, f, indent=4)

In [19]:
f = open('question.json', 'r')
question = json.load(f)

In [20]:
def get_info(question) :
    question_data = json.loads(question['question_data'])
    board = question_data['board']
    general = question_data['general']

    #preprocess board
    height = board['height']
    width = board['width']
    start_board = board['start']
    end_board = board['goal']
    print('width and height of board:', width, height)
    start_board = np.array(start_board)
    end_board = np.array(end_board)

    #preprocess general
    n = general['n']

    general_patterns = []
    for i in general["patterns"]:
        p = i["p"]
        width = i["width"]
        height = i["height"]
        print(f'width and height of general patterns {p}:',width, height)
        cells = i["cells"]
        cells = np.array(cells)
        general_patterns.append(Pattern(height, width, board = cells))
    return start_board, end_board, general_patterns

In [21]:
start_board, end_board, general_patterns = get_info(question)


width and height of board: 128 64
width and height of general patterns 25: 150 85
width and height of general patterns 26: 166 14
(64, 128)
(64, 128)


In [24]:
compare = np.zeros((start_board.shape[0], start_board.shape[1]))
for i in range(start_board.shape[0]):
    for j in range(start_board.shape[1]):
        if start_board[i][j] == end_board[i][j]:
            compare[i][j] = 1
#save compare to file
np.savetxt('compare.txt', compare, fmt='%d')
np.savetxt('compare.T.txt', compare.T, fmt='%d')

[[1. 1. 1. ... 1. 0. 0.]
 [1. 1. 1. ... 1. 0. 1.]
 [1. 1. 1. ... 1. 0. 0.]
 ...
 [1. 0. 0. ... 0. 1. 1.]
 [0. 0. 0. ... 0. 1. 1.]
 [0. 0. 0. ... 0. 0. 0.]]


In [32]:
m = start_board.shape[0]
n = start_board.shape[1]
print(m,n)

game = Game(m, n, start_board, end_board, general_patterns)

64 128
3012224


In [28]:
#test patterns
print(game.grid.patterns[24].pattern)

[[1 0 1 ... 0 1 0]
 [1 0 1 ... 0 1 0]
 [1 0 1 ... 0 1 0]
 ...
 [1 0 1 ... 0 1 0]
 [1 0 1 ... 0 1 0]
 [1 0 1 ... 0 1 0]]


In [11]:
def check(board, final_board, x,y,p,q):
    while x < 0: x+=1
    while y < 0: y+=1
    if x <= 92: return False
    if board[x][y] == final_board[x][y]:
        return False
    return True

In [29]:
cur_board = game.grid.board.copy()
final_board = game.final_grid.board.copy()

#### Count the number of valid move

In [13]:
# cnt = 0
# for i in range(0, len(game.dict)):
#     # if i % 500 == 0: 
#     x,y, direction, id = game.dict[i]
#     p,q,type = game.grid.patterns[id].p, game.grid.patterns[id].q, game.grid.patterns[id].id
#     if(not check(cur_board, final_board, x,y,p,q)): continue
#     cnt += 1
# print("Numbebr of valid moves: ", cnt)

In [31]:
game_clone.grid.board[0][0] = 4
print(game.grid.board[0][0] )

4


In [19]:
import time
best_reward = 9999999
t1 = time.time()
ok = False
for id in range(len(game.grid.patterns)):
        for y in range(n):
            for direction in range(4):
                if direction == 3 or x != 8 or x != 0: continue
        # if i % 500 == 0: 
                
                i = game.convert(97, y, direction, id)

                board, reward, done, _, _= game.fake_step(i)
            
                if reward < best_reward:
                # if True:
                    print(f"step {i}: x = {x}, y = {y}, direction = {direction}, id = {id} with reward = {reward}")
                    print(cntDiff(m, n, board, final_board))
                    best_reward = reward
                if done:
                    print("found")
                    #save this pattern to file
                    x,y, direction, p = game.dict[i]
                    print('total time: ', time.time() - t1)
                    #example: {"n": 1, "ops": [{"x": 1, "y": 1, "s": 1, "p": 1}]}
                    with open('answer2.json', 'w') as f:
                        json.dump({"n": 1, "ops": [{"x": y, "y": x, "s": direction, "p": p}]}, f, indent=4)
                    #break all for loop
                    ok = True
                    break
            if ok: break
        if ok: break

    
else: 
    print('not found')
    print('total time: ', time.time() - t1)

step 6208: x = 97, y = 0, direction = 0, id = 0 with reward = 1523
1523
1523
step 106219: x = 97, y = 0, direction = 0, id = 3 with reward = 1521
1521
1521
step 175199: x = 97, y = 0, direction = 0, id = 5 with reward = 1519
1519
1519
step 210307: x = 97, y = 0, direction = 0, id = 6 with reward = 1517
1517
1517
step 362595: x = 97, y = 0, direction = 0, id = 10 with reward = 1516
1516
1516
step 452971: x = 97, y = 0, direction = 0, id = 12 with reward = 1515
1515
1515
step 561907: x = 97, y = 0, direction = 0, id = 14 with reward = 1509
1509
1509
step 3024856: x = 97, y = 0, direction = 0, id = 25 with reward = 1496
1496
1496
step 385189: x = 97, y = 0, direction = 2, id = 10 with reward = 1486
1486
1486
step 531697: x = 97, y = 0, direction = 2, id = 13 with reward = 1461
1461
1461
step 933509: x = 97, y = 0, direction = 2, id = 18 with reward = 779
779
779
step 933511: x = 97, y = 2, direction = 2, id = 18 with reward = 769
769
769
step 957769: x = 97, y = 3, direction = 3, id = 18 

KeyboardInterrupt: 

In [27]:
# def solve(question):
#     return {"n": 1, "ops": [{"x": 3, "y": 97, "s": 3, "p": 18}]}

In [30]:
# steps = solve(question)
# print(steps)
steps = json.load(open('answer.json', 'r'))
# send your answer to server
try:
    payload = {"question_id": question_id, "answer_data": steps}
    res = requests.post(f"{url}/answer", json=payload, headers=headers).json()

except requests.exceptions.RequestException as e:
    print(f"Error: {e}")
#  get your answer id
answer_id = res["id"]

# get your answer and score from server


{'n': 1, 'ops': [{'x': 3, 'y': 97, 's': 3, 'p': 18}]}


In [22]:
print(res)

{'id': 312}


In [24]:

print(answer_id)

312


In [31]:
answer = requests.get(f"{url}/answer/{answer_id}", headers=headers).json()
score_data = json.loads(answer["score_data"])
print('match count: ', score_data["match_count"])
print("final score:", score_data["final_score"])

match count:  8192
final score: 8183.7


In [14]:
start_board = np.load('board.npy')
print(start_board)

[[2 2 1 ... 0 0 0]
 [2 3 1 ... 1 3 0]
 [1 2 2 ... 0 3 2]
 ...
 [3 2 0 ... 1 2 1]
 [1 3 3 ... 1 1 3]
 [0 2 3 ... 1 0 3]]


In [12]:
game2 = Game(16,16,20)

1254784


In [13]:
cur_board = game2.grid.board.copy()
print(cur_board)

[[1 0 3 1 2 1 2 2 0 2 0 3 0 0 3 2]
 [2 0 0 1 0 2 2 2 1 2 0 2 0 2 2 2]
 [3 1 0 1 0 2 2 3 0 2 1 1 3 0 3 2]
 [1 2 0 2 1 2 1 0 2 2 3 3 3 2 3 3]
 [3 2 0 2 0 3 3 2 1 3 1 2 0 3 2 1]
 [2 2 2 3 1 2 0 1 0 3 3 2 0 1 2 1]
 [3 2 1 1 3 3 2 1 0 1 0 3 3 2 0 3]
 [2 2 2 0 1 1 1 2 3 3 2 0 3 0 1 3]
 [1 0 2 0 1 3 3 0 3 2 1 3 2 0 3 2]
 [2 1 1 0 3 0 0 3 1 0 2 2 2 2 2 1]
 [1 0 2 2 0 3 3 3 0 0 0 1 1 0 3 3]
 [3 1 0 2 3 2 0 2 2 1 0 3 0 1 2 0]
 [0 3 1 1 3 2 1 1 0 2 2 2 1 1 0 0]
 [0 1 2 2 2 1 2 1 0 2 2 0 3 1 0 1]
 [1 2 1 1 3 1 0 3 0 1 1 2 0 0 3 2]
 [1 0 0 1 3 2 0 3 0 0 3 3 3 3 3 2]]


In [26]:
board, reward, done, _, _= game2.fake_step(game2.convert(0,0,0,0))

1566