In [1]:
import numpy as np
import matplotlib.pyplot as plt
import gym
import pygame
import requests
import json
import numpy as np
import sys
import os

sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '../..')))

from pattern import Pattern
from game import Game

pygame 2.5.2 (SDL 2.28.3, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
from grid import apply_shift

### If not having question file or new question required, run this cell

In [5]:
question_id = 70

In [7]:
url = "https://proconvn.duckdns.org"
headers = {"Authorization": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIsIm5hbWUiOiJQVElUIiwiaXNfYWRtaW4iOmZhbHNlLCJpYXQiOjE3MjgyMTE5MzYsImV4cCI6MTcyODM4NDczNn0.fPkOgq9m6Z3_vbRFaL0EUTmK2wioCbuCqnpxKrmTkLA"}

# question = requests.get(f"{url}/question/{question_id}", headers=headers).json()

# with open('question.json', 'w') as f:
#     json.dump(question, f, indent=4)

In [8]:
f = open('question.json', 'r')
question = json.load(f)

In [9]:
def get_info(question) :
    question_data = json.loads(question['question_data'])
    board = question_data['board']
    general = question_data['general']

    #preprocess board
    height = board['height']
    width = board['width']
    start_board = board['start']
    end_board = board['goal']
    print('width and height of board:', width, height)
    start_board = np.array(start_board)
    end_board = np.array(end_board)

    #preprocess general
    n = general['n']

    general_patterns = []
    for i in general["patterns"]:
        p = i["p"]
        width = i["width"]
        height = i["height"]
        print(f'width and height of general patterns {p}:',width, height)
        cells = i["cells"]
        cells = np.array(cells)
        general_patterns.append(Pattern(height, width, board = cells))
    return start_board, end_board, general_patterns

In [10]:
start_board, end_board, general_patterns = get_info(question)


width and height of board: 128 64
width and height of general patterns 25: 150 85
width and height of general patterns 26: 166 14


In [ ]:
def sol2(start_board, end_board, row, col, )

In [11]:
compare = np.zeros((start_board.shape[0], start_board.shape[1]))
for i in range(start_board.shape[0]):
    for j in range(start_board.shape[1]):
        if start_board[i][j] == end_board[i][j]:
            compare[i][j] = 1
#save compare to file
np.savetxt('compare.txt', compare, fmt='%d')
np.savetxt('compare.T.txt', compare.T, fmt='%d')

In [9]:
m = start_board.shape[0]
n = start_board.shape[1]
print(m,n)

game = Game(m = m, n = n, start_board= start_board, end_board= end_board,patterns= general_patterns)

64 128
3266452


In [10]:
#test patterns
print(game.grid.patterns[25].pattern)

[[0 0 0 ... 1 0 1]
 [1 0 1 ... 1 1 1]
 [0 1 0 ... 0 0 0]
 ...
 [1 1 0 ... 1 1 0]
 [0 0 1 ... 0 0 0]
 [1 1 0 ... 0 0 1]]


In [11]:
def check(board, final_board, x,y,p,q):
    while x < 0: x+=1
    while y < 0: y+=1
    if x <= 92: return False
    if board[x][y] == final_board[x][y]:
        return False
    return True

In [12]:
cur_board = game.grid.board.copy()
final_board = game.final_grid.board.copy()

#### Count the number of valid move

In [13]:
# cnt = 0
# for i in range(0, len(game.dict)):
#     # if i % 500 == 0: 
#     x,y, direction, id = game.dict[i]
#     p,q,type = game.grid.patterns[id].p, game.grid.patterns[id].q, game.grid.patterns[id].id
#     if(not check(cur_board, final_board, x,y,p,q)): continue
#     cnt += 1
# print("Numbebr of valid moves: ", cnt)

In [13]:
def cntDiff(m, n, cur_board, final_board):
    cnt=0
    for i in range(m):
        for j in range(n):
            if(cur_board[i][j] != final_board[i][j]): cnt+=1
    
    return cnt

In [14]:
import time
best_reward = 9999999
t1 = time.time()
ok = False
cur_x, cur_y, cur_direction, cur_id = 0, 0, 0, 0
for x,y in [(8, 0), (0,24)]:
    for id in range(25, len(game.grid.patterns)):
        for y in range(n):
            for direction in range(4):
                
        # if i % 500 == 0: 
                # if direction == 1: continue
                i = game.convert(8, y, direction, id)

                next_board = apply_shift(cur_board, 8, y, game.grid.patterns[id], direction)
                reward = cntDiff(m,n,next_board, final_board)
                if reward < best_reward:
                # if True:
                    print(f"step {i}: x = {x}, y = {y}, direction = {direction}, id = {id} with reward = {reward}")
                   # print(cntDiff(m, n, board, final_board))
                    best_reward = reward
                    cur_x, cur_y, cur_direction, cur_id = 8, y, direction, id

print('total time: ', time.time() - t1)

step 3037857: x = 8, y = 0, direction = 0, id = 25 with reward = 5985
step 3160845: x = 8, y = 0, direction = 3, id = 25 with reward = 5925
step 3160866: x = 8, y = 21, direction = 3, id = 25 with reward = 5893
step 3160867: x = 8, y = 22, direction = 3, id = 25 with reward = 5863
total time:  190.20538187026978


In [ ]:
board, reward, _, _, _ = game.step(game.convert(cur_x, cur_y, cur_direction, cur_id))
print(reward)


In [27]:
# def solve(question):
#     return {"n": 1, "ops": [{"x": 3, "y": 97, "s": 3, "p": 18}]}

In [30]:
# steps = solve(question)
# print(steps)
steps = json.load(open('answer.json', 'r'))
# send your answer to server
try:
    payload = {"question_id": question_id, "answer_data": steps}
    res = requests.post(f"{url}/answer", json=payload, headers=headers).json()

except requests.exceptions.RequestException as e:
    print(f"Error: {e}")
#  get your answer id
answer_id = res["id"]

# get your answer and score from server


{'n': 1, 'ops': [{'x': 3, 'y': 97, 's': 3, 'p': 18}]}


In [22]:
print(res)

{'id': 312}


In [24]:

print(answer_id)

312


In [31]:
answer = requests.get(f"{url}/answer/{answer_id}", headers=headers).json()
score_data = json.loads(answer["score_data"])
print('match count: ', score_data["match_count"])
print("final score:", score_data["final_score"])

match count:  8192
final score: 8183.7


In [14]:
start_board = np.load('board.npy')
print(start_board)

[[2 2 1 ... 0 0 0]
 [2 3 1 ... 1 3 0]
 [1 2 2 ... 0 3 2]
 ...
 [3 2 0 ... 1 2 1]
 [1 3 3 ... 1 1 3]
 [0 2 3 ... 1 0 3]]


In [12]:
game2 = Game(16,16,20)

1254784


In [13]:
cur_board = game2.grid.board.copy()
print(cur_board)

[[1 0 3 1 2 1 2 2 0 2 0 3 0 0 3 2]
 [2 0 0 1 0 2 2 2 1 2 0 2 0 2 2 2]
 [3 1 0 1 0 2 2 3 0 2 1 1 3 0 3 2]
 [1 2 0 2 1 2 1 0 2 2 3 3 3 2 3 3]
 [3 2 0 2 0 3 3 2 1 3 1 2 0 3 2 1]
 [2 2 2 3 1 2 0 1 0 3 3 2 0 1 2 1]
 [3 2 1 1 3 3 2 1 0 1 0 3 3 2 0 3]
 [2 2 2 0 1 1 1 2 3 3 2 0 3 0 1 3]
 [1 0 2 0 1 3 3 0 3 2 1 3 2 0 3 2]
 [2 1 1 0 3 0 0 3 1 0 2 2 2 2 2 1]
 [1 0 2 2 0 3 3 3 0 0 0 1 1 0 3 3]
 [3 1 0 2 3 2 0 2 2 1 0 3 0 1 2 0]
 [0 3 1 1 3 2 1 1 0 2 2 2 1 1 0 0]
 [0 1 2 2 2 1 2 1 0 2 2 0 3 1 0 1]
 [1 2 1 1 3 1 0 3 0 1 1 2 0 0 3 2]
 [1 0 0 1 3 2 0 3 0 0 3 3 3 3 3 2]]


In [26]:
board, reward, done, _, _= game2.fake_step(game2.convert(0,0,0,0))

1566